FROM mongo:latest


# The python stuff is breaking it!

#RUN apt-get update
#RUN apt-get install -y apt-utils
#RUN apt-get install -y python python-dev python-distribute python-pip

#RUN pip install pymongo

#COPY setup.py setup.py

#CMD python setup.py

